### PR TITLE
Translations update from Hosted Weblate

### PR DESCRIPTION
**Pull request by weblate**
Translations update from [Hosted Weblate](https://hosted.weblate.org) for [Gauguin/Gauguin](https://hosted.weblate.org/projects/gauguin/gauguin/).

It also includes following components:

* [Gauguin/Gauguin Metadata](https://hosted.weblate.org/projects/gauguin/gauguin-metadata/)

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by meikpiep** [comment]
@hasecilu @augustwollter Thanks for translating Gauguin!

**Comment by hasecilu** [comment]
> @hasecilu @augustwollter Thanks for translating Gauguin!

Sure, no problem, it's a fun game. Nice to have screenshots as help.

Since for each language some words could be translated differently by translators having activated the **Glossary** will be helpful as a guide to translate certain words, could it be enabled? Didn't find it anywhere.

**Comment by HarmfulBreeze** [comment]
There never really was a glossary so far. The Gauguin Weblate component was declared as a glossary, but it really wasn't, it was actually the main translation project.
I don't see any particular reason not to create a separate Glossary component. That's how Fedora does it for instance: https://translate.fedoraproject.org/projects/anaconda-webui/

I can take care of it if need be, but it should really just be about creating the component and checking the Use as a glossary checkbox.

**Comment by HarmfulBreeze** [comment]
@meikpiep @hasecilu
The glossary is now up! I used TermBase eXchange (TBX) as it's an international standard for terminology. [More info on Wikipedia](https://en.wikipedia.org/wiki/TermBase_eXchange) (Also that's used by Fedora and others so... That was a safe pick.)

I also reused the settings for the main Gauguin component, therefore, suggestions require two votes to be approved.

You can find the glossary component here: https://hosted.weblate.org/projects/gauguin/glossary/

**Comment by hasecilu** [comment]
Hello, just took a look here, I'm trying to add some terms into the glossary but there is no such option on Weblate UI.
For example when I'm on KiCad project, there is a button that says `Add term to glossary`. It could be a permission issue?

**Pull request merged**
